# Copyright (c) 2019-2022, NVIDIA CORPORATION.

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        # Use the config file specific to each subproject so that each
        # project can specify its own first/third-party packages.
        args: ["--config-root=python/", "--resolve-all-configs"]
        files: python/.*
        types_or: [python, cython, pyi]
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        files: python/.*
        args: ["--config", "python/pyproject.toml"]
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: ["--config=python/setup.cfg"]
        files: python/.*$
        types: [file]
        types_or: [python, cython]
        additional_dependencies: ["flake8-force"]
  - repo: https://github.com/MarcoGorelli/cython-lint
    rev: v0.1.10
    hooks:
      - id: cython-lint
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.971'
    hooks:
      - id: mypy
        additional_dependencies: [types-cachetools]
        args: ["--config-file=python/setup.cfg",
                "python/kvikio",
                "python/tests",
                "python/examples",
                "python/benchmarks"]
        pass_filenames: false
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v11.1.0
    hooks:
      - id: clang-format
        types_or: [c, c++, cuda]
        args: ["-fallback-style=none", "-style=file", "-i"]
  - repo: local
    hooks:
      - id: copyright-check
        name: copyright-check
        entry: python ./ci/checks/copyright.py --git-modified-only --update-current-year
        language: python
        pass_filenames: false
        additional_dependencies: [gitpython]
  - repo: https://github.com/codespell-project/codespell
    rev: v2.1.0
    hooks:
      - id: codespell
        exclude: |
          (?x)^(
            ^CHANGELOG.md$|
            ^.*versioneer.py$
          )

default_language_version:
      python: python3
